removert:

  # @ NOTE: Recommended test regions and corresponding parameters
  # - KITTI 09 [downsample_voxel_size: 0.05m, skips: 5, start idx: 1300, end idx: 1600] 
  # - KITTI 03 [downsample_voxel_size: 0.05m, skips: 5, start idx: 0, end idx: 150] 

  isScanFileKITTIFormat: true

  # @ save option 
  saveMapPCD: true 
  saveCleanScansPCD: true

  sequence_vfov: 50 # including upper and lower fovs, for example, KITTI's HDL64E is 2 + 24.9 ~ 27 deg. (so 25 + 25 = 50 is recommended because it is enough)
  sequence_hfov: 360 # generally for targetting scanning LiDAR but a lidar having restricted hfov also just can use the 360 (because no point regions are considered in the algorithm)

  # @ Sampling nodes 
  use_keyframe_gap: true 
  keyframe_gap: 5 # i.e., 5 means every 5 frames // 5 is recommended for fast removing while preserving the static map's quality # if you make all scans clean, use this value = 1
  # keyframe_gap: 2 # i.e., 5 means every 5 frames // 5 is recommended for fast removing while preserving the static map's quality # if you make all scans clean, use this value = 1

  # @ auto repeat
  #   means the removeter runs on all scans in a sequence 
  clean_for_all_scan: false # default is false
  batch_size: 150
  valid_ratio_to_save: 0.75 # i.e., no save cleaned scans located at the boundaries of a batch  


  # @ Range image resolution
  # the below is actually magnifier ratio (i.e., 5 means x5 resolution, the x1 means 1 deg x 1 deg per pixel)
  # - recommend to use the first removing resolution's magnifier ratio should meet the seonsor vertical fov / number of rays 
  #     - e.g., HDL 64E of KITTI dataset -> appx 25 deg / 64 ray ~ 0.4 deg per pixel -> the magnifier ratio = 1/0.4 = 2.5
  #     - e.g., Ouster OS1-64 of MulRan dataset -> appx 45 deg / 64 ray ~ 0.7 deg per pixel -> the magnifier ratio = 1/0.7 = 1.4
  # - recommend to use the first reverting resolution's magnifier ratio should lied in 1.0 to 1.5
  remove_resolution_list: [2.5, 2.2, 2] # for HDL 64E of KITTI dataset -> Same with ERASOR paper benchmarking
  # remove_resolution_list: [1.4, 1.1] # for Ouster OS1-64 of MulRan dataset

  # @ Removert params 
  # about density 
  downsample_voxel_size: 0.01 # user parameter but recommend to use 0.05 to make sure an enough density (this value is related to the removing resolution's expected performance)

  # about Static sensitivity (you need to tune these below two values, depends on the environement)
  # - if you use a raw scan 
  num_nn_points_within: 2 # how many - using higher, more strict static 
  dist_nn_points_within: 0.1 # meter - using smaller, more strict static 

  # about Static sensitivity (SC-LIO-SAM's feature cloud)
  # - if you use a SC-LIO-SAM's feature cloud
  # num_nn_points_within: 2 # how many - using higher, more strict static 
  # dist_nn_points_within: 0.2 # meter - using smaller, more strict static 

  # @ For faster
  num_omp_cores: 16 # for faster map points projection (to make a map range image)

  # @ For visualization of range images (rviz -d removert_visualization.rviz)
  rimg_color_min: 0.0 # meter
  rimg_color_max: 20.0 # meter

  replace_intensity: false